/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateVerificationCodeRequest,
  CreateVerificationCodeRespones,
} from '../models';
import {
    CreateVerificationCodeRequestFromJSON,
    CreateVerificationCodeRequestToJSON,
    CreateVerificationCodeResponesFromJSON,
    CreateVerificationCodeResponesToJSON,
} from '../models';

export interface CreateVerificationCodeOperationRequest {
    createVerificationCodeRequest?: CreateVerificationCodeRequest;
}

/**
 * 
 */
export class VerificationApi extends runtime.BaseAPI {

    /**
     */
    async createVerificationCodeRaw(requestParameters: CreateVerificationCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateVerificationCodeRespones>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/verification/code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVerificationCodeRequestToJSON(requestParameters.createVerificationCodeRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateVerificationCodeResponesFromJSON(jsonValue));
    }

    /**
     */
    async createVerificationCode(requestParameters: CreateVerificationCodeOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateVerificationCodeRespones> {
        const response = await this.createVerificationCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
