/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
} from './Account';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
} from './Pagination';

/**
 * Account list
 * @export
 * @interface AccountList
 */
export interface AccountList {
    /**
     * 
     * @type {Array<Account>}
     * @memberof AccountList
     */
    data: Array<Account>;
    /**
     * 
     * @type {Pagination}
     * @memberof AccountList
     */
    pagination: Pagination;
}

/**
 * Check if a given object implements the AccountList interface.
 */
export function instanceOfAccountList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "pagination" in value;

    return isInstance;
}

export function AccountListFromJSON(json: any): AccountList {
    return AccountListFromJSONTyped(json, false);
}

export function AccountListFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AccountFromJSON)),
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function AccountListToJSON(value?: AccountList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AccountToJSON)),
        'pagination': PaginationToJSON(value.pagination),
    };
}

