/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTicketChallenge
 */
export interface CreateTicketChallenge {
    /**
     * 
     * @type {string}
     * @memberof CreateTicketChallenge
     */
    email: string;
}

/**
 * Check if a given object implements the CreateTicketChallenge interface.
 */
export function instanceOfCreateTicketChallenge(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function CreateTicketChallengeFromJSON(json: any): CreateTicketChallenge {
    return CreateTicketChallengeFromJSONTyped(json, false);
}

export function CreateTicketChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTicketChallenge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function CreateTicketChallengeToJSON(value?: CreateTicketChallenge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

