/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VerificationCodePurpose } from './VerificationCodePurpose';
import {
    VerificationCodePurposeFromJSON,
    VerificationCodePurposeFromJSONTyped,
    VerificationCodePurposeToJSON,
} from './VerificationCodePurpose';

/**
 * 
 * @export
 * @interface CreateVerificationCodeRequest
 */
export interface CreateVerificationCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateVerificationCodeRequest
     */
    email?: string;
    /**
     * 
     * @type {VerificationCodePurpose}
     * @memberof CreateVerificationCodeRequest
     */
    purpose: VerificationCodePurpose;
}

/**
 * Check if a given object implements the CreateVerificationCodeRequest interface.
 */
export function instanceOfCreateVerificationCodeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "purpose" in value;

    return isInstance;
}

export function CreateVerificationCodeRequestFromJSON(json: any): CreateVerificationCodeRequest {
    return CreateVerificationCodeRequestFromJSONTyped(json, false);
}

export function CreateVerificationCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVerificationCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'purpose': VerificationCodePurposeFromJSON(json['purpose']),
    };
}

export function CreateVerificationCodeRequestToJSON(value?: CreateVerificationCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'purpose': VerificationCodePurposeToJSON(value.purpose),
    };
}

