/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Login request
 * @export
 * @interface CreateSessionRequest
 */
export interface CreateSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    totpCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    verificationCode?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSessionRequest
     */
    tickets?: Array<string>;
}

/**
 * Check if a given object implements the CreateSessionRequest interface.
 */
export function instanceOfCreateSessionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateSessionRequestFromJSON(json: any): CreateSessionRequest {
    return CreateSessionRequestFromJSONTyped(json, false);
}

export function CreateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'totpCode': !exists(json, 'totpCode') ? undefined : json['totpCode'],
        'verificationCode': !exists(json, 'verificationCode') ? undefined : json['verificationCode'],
        'tickets': !exists(json, 'tickets') ? undefined : json['tickets'],
    };
}

export function CreateSessionRequestToJSON(value?: CreateSessionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'totpCode': value.totpCode,
        'verificationCode': value.verificationCode,
        'tickets': value.tickets,
    };
}

