/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ordering
 * @export
 */
export const Ordering = {
    Ascending: 'ASCENDING',
    Descending: 'DESCENDING'
} as const;
export type Ordering = typeof Ordering[keyof typeof Ordering];


export function OrderingFromJSON(json: any): Ordering {
    return OrderingFromJSONTyped(json, false);
}

export function OrderingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ordering {
    return json as Ordering;
}

export function OrderingToJSON(value?: Ordering | null): any {
    return value as any;
}

