/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PubKeyCredParam
 */
export interface PubKeyCredParam {
    /**
     * 
     * @type {string}
     * @memberof PubKeyCredParam
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof PubKeyCredParam
     */
    alg: number;
}

/**
 * Check if a given object implements the PubKeyCredParam interface.
 */
export function instanceOfPubKeyCredParam(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "alg" in value;

    return isInstance;
}

export function PubKeyCredParamFromJSON(json: any): PubKeyCredParam {
    return PubKeyCredParamFromJSONTyped(json, false);
}

export function PubKeyCredParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubKeyCredParam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'alg': json['alg'],
    };
}

export function PubKeyCredParamToJSON(value?: PubKeyCredParam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'alg': value.alg,
    };
}

