/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServiceType = {
    Iaas: 'IAAS',
    Paas: 'PAAS',
    Saas: 'SAAS'
} as const;
export type ServiceType = typeof ServiceType[keyof typeof ServiceType];


export function ServiceTypeFromJSON(json: any): ServiceType {
    return ServiceTypeFromJSONTyped(json, false);
}

export function ServiceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceType {
    return json as ServiceType;
}

export function ServiceTypeToJSON(value?: ServiceType | null): any {
    return value as any;
}

