/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Session verification request
 * @export
 * @interface SessionVerificationRequest
 */
export interface SessionVerificationRequest {
    /**
     * 
     * @type {string}
     * @memberof SessionVerificationRequest
     */
    token: string;
}

/**
 * Check if a given object implements the SessionVerificationRequest interface.
 */
export function instanceOfSessionVerificationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function SessionVerificationRequestFromJSON(json: any): SessionVerificationRequest {
    return SessionVerificationRequestFromJSONTyped(json, false);
}

export function SessionVerificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionVerificationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function SessionVerificationRequestToJSON(value?: SessionVerificationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

