/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SessionStatus = {
    Actived: 'ACTIVED',
    TwoFa: 'TWO_FA',
    Expired: 'EXPIRED',
    Disactived: 'DISACTIVED'
} as const;
export type SessionStatus = typeof SessionStatus[keyof typeof SessionStatus];


export function SessionStatusFromJSON(json: any): SessionStatus {
    return SessionStatusFromJSONTyped(json, false);
}

export function SessionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionStatus {
    return json as SessionStatus;
}

export function SessionStatusToJSON(value?: SessionStatus | null): any {
    return value as any;
}

