/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TicketType = {
    Password: 'PASSWORD',
    Email: 'EMAIL',
    Totp: 'TOTP',
    Webauthn: 'WEBAUTHN'
} as const;
export type TicketType = typeof TicketType[keyof typeof TicketType];


export function TicketTypeFromJSON(json: any): TicketType {
    return TicketTypeFromJSONTyped(json, false);
}

export function TicketTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketType {
    return json as TicketType;
}

export function TicketTypeToJSON(value?: TicketType | null): any {
    return value as any;
}

