/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Totp
 */
export interface Totp {
    /**
     * 
     * @type {string}
     * @memberof Totp
     */
    url: string;
}

/**
 * Check if a given object implements the Totp interface.
 */
export function instanceOfTotp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function TotpFromJSON(json: any): Totp {
    return TotpFromJSONTyped(json, false);
}

export function TotpFromJSONTyped(json: any, ignoreDiscriminator: boolean): Totp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function TotpToJSON(value?: Totp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

