/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePasswordRequest
 */
export interface UpdatePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePasswordRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePasswordRequest
     */
    verificationCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePasswordRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePasswordRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the UpdatePasswordRequest interface.
 */
export function instanceOfUpdatePasswordRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "newPassword" in value;

    return isInstance;
}

export function UpdatePasswordRequestFromJSON(json: any): UpdatePasswordRequest {
    return UpdatePasswordRequestFromJSONTyped(json, false);
}

export function UpdatePasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'verificationCode': !exists(json, 'verificationCode') ? undefined : json['verificationCode'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'newPassword': json['newPassword'],
    };
}

export function UpdatePasswordRequestToJSON(value?: UpdatePasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'verificationCode': value.verificationCode,
        'password': value.password,
        'newPassword': value.newPassword,
    };
}

