/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VerificationCodePurpose = {
    CreateAccount: 'CREATE_ACCOUNT',
    SetPassword: 'SET_PASSWORD',
    Signin: 'SIGNIN',
    Create2Fa: 'CREATE_2FA',
    Ticket: 'TICKET'
} as const;
export type VerificationCodePurpose = typeof VerificationCodePurpose[keyof typeof VerificationCodePurpose];


export function VerificationCodePurposeFromJSON(json: any): VerificationCodePurpose {
    return VerificationCodePurposeFromJSONTyped(json, false);
}

export function VerificationCodePurposeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationCodePurpose {
    return json as VerificationCodePurpose;
}

export function VerificationCodePurposeToJSON(value?: VerificationCodePurpose | null): any {
    return value as any;
}

