/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VerificationCodeResult = {
    SuccessCreated: 'SUCCESS_CREATED',
    Frequent: 'FREQUENT',
    AccountExists: 'ACCOUNT_EXISTS'
} as const;
export type VerificationCodeResult = typeof VerificationCodeResult[keyof typeof VerificationCodeResult];


export function VerificationCodeResultFromJSON(json: any): VerificationCodeResult {
    return VerificationCodeResultFromJSONTyped(json, false);
}

export function VerificationCodeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationCodeResult {
    return json as VerificationCodeResult;
}

export function VerificationCodeResultToJSON(value?: VerificationCodeResult | null): any {
    return value as any;
}

