/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebAuthnResponse
 */
export interface WebAuthnResponse {
    /**
     * 
     * @type {string}
     * @memberof WebAuthnResponse
     */
    attestationObject: string;
    /**
     * 
     * @type {string}
     * @memberof WebAuthnResponse
     */
    clientDataJSON: string;
}

/**
 * Check if a given object implements the WebAuthnResponse interface.
 */
export function instanceOfWebAuthnResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attestationObject" in value;
    isInstance = isInstance && "clientDataJSON" in value;

    return isInstance;
}

export function WebAuthnResponseFromJSON(json: any): WebAuthnResponse {
    return WebAuthnResponseFromJSONTyped(json, false);
}

export function WebAuthnResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthnResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attestationObject': json['attestationObject'],
        'clientDataJSON': json['clientDataJSON'],
    };
}

export function WebAuthnResponseToJSON(value?: WebAuthnResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attestationObject': value.attestationObject,
        'clientDataJSON': value.clientDataJSON,
    };
}

