/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebauthnUser
 */
export interface WebauthnUser {
    /**
     * 
     * @type {string}
     * @memberof WebauthnUser
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnUser
     */
    displayName: string;
}

/**
 * Check if a given object implements the WebauthnUser interface.
 */
export function instanceOfWebauthnUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "displayName" in value;

    return isInstance;
}

export function WebauthnUserFromJSON(json: any): WebauthnUser {
    return WebauthnUserFromJSONTyped(json, false);
}

export function WebauthnUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebauthnUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'displayName': json['displayName'],
    };
}

export function WebauthnUserToJSON(value?: WebauthnUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'displayName': value.displayName,
    };
}

