/* tslint:disable */
/* eslint-disable */
/**
 * BoardWare Cloud APIs
 * BoardWare cloud console api
 *
 * The version of the OpenAPI document: 0.0.12
 * Contact: dan.chen@boardware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PublicKey } from './PublicKey';
import {
    PublicKeyFromJSON,
    PublicKeyFromJSONTyped,
    PublicKeyToJSON,
} from './PublicKey';

/**
 * 
 * @export
 * @interface WebAuthnSession
 */
export interface WebAuthnSession {
    /**
     * 
     * @type {string}
     * @memberof WebAuthnSession
     */
    id: string;
    /**
     * 
     * @type {PublicKey}
     * @memberof WebAuthnSession
     */
    publicKey: PublicKey;
}

/**
 * Check if a given object implements the WebAuthnSession interface.
 */
export function instanceOfWebAuthnSession(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "publicKey" in value;

    return isInstance;
}

export function WebAuthnSessionFromJSON(json: any): WebAuthnSession {
    return WebAuthnSessionFromJSONTyped(json, false);
}

export function WebAuthnSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebAuthnSession {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'publicKey': PublicKeyFromJSON(json['publicKey']),
    };
}

export function WebAuthnSessionToJSON(value?: WebAuthnSession | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'publicKey': PublicKeyToJSON(value.publicKey),
    };
}

